version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rehearsal_scheduler
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/rehearsal_scheduler
      - JWT_SECRET=dev_jwt_secret
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment: []
    ports:
      - "3000:3000"